### ISSUE TITLE
made extra exercise

### ISSUE THREAD

**Issue by Alexikon** [htl-perg-2019-20-5ahif/travel-planner-api-Alexikon#1]
Mr. Stropek, I made the bonus exercise. (Just don't use https)

I did not write a .net 2.1 library, because when I tried it, 
my API could not find the library even on public.
In my API I wrote the Business Logic to the Services folder.

Moreover, the first time I used LINQ to solve the problem because 
nested foreach'es look horrible.

**Comment by Alexikon** [comment]
did I get the extra point?

**Comment by rstropek** [comment]
Yes, you did.
